<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/styles/style.css">
    <title>Document</title>
</head>
<body>
    <br><br><br>
  <h1>Félicitations, vous avez réussi a atteindre le chateau de la princesse</h1>
  <br><br>
  <img src="assets/styles/chateau.png" alt="">
  <p>Le chevalier et la princesse ont réussi à se retrouver. Ils vont maintenant pouvoir vivre une vie paisible</p>
</body>
</html>