<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/styles/style.css">
    <title>Document</title>
</head>
<body>
    <br><br><br>
  <h1>Vous êtes mort</h1>
  <br><br>
  <img src="assets/styles/tetedemort.png" alt="">
  <br>
  <p> Lors de la traversée de la prairie, vous êtes tombé sur une meute de loup devorant un troupeau d'agneau,
    ils en ont profité en vous dévorant vous aussi.</p>
    <br>
</body>
</html>